### ISSUE TITLE
建议把配置保存到当前目录下的ini文件中

### ISSUE THREAD

**Issue by ohyeah521** [kenvix/USBCopyer#13]
建议把配置保存到当前目录下的ini文件中

升级新版本配置丢失，不知道你是不是写注册表了，还是怎么弄的，建议保存到本地目录，方便移动

**Comment by kenvix** [comment]
C:\Users\[USERNAME]\AppData\Local\Kenvix

**Comment by kenvix** [comment]
新版将会保存到设置到当前目录.

**Comment by kenvix** [comment]
已实现
