### ISSUE TITLE
文件冲突解决方案的问题

### ISSUE THREAD

**Issue by fineemb** [kenvix/USBCopyer#16]
我设置的是重命名新文件. 同一个ID的U盘, 里面的A.file文件如果文件被修改过再次复制的时候, 没有把修改过的文件重命名复制过来.
这样可以备份文件的历史版本, 这是很实用的场景
参考https://www.usbflashcopy.com/

**Comment by kenvix** [comment]
先等我高考完╮(￣▽￣)╭

**Comment by fineemb** [comment]
哦,加油!!

**Comment by kenvix** [comment]
请详细说明
