### ISSUE TITLE
【预览】 USBCopyer V5.0

### ISSUE THREAD

**Issue by kenvix** [kenvix/USBCopyer#18]
![11](https://user-images.githubusercontent.com/4546175/41191127-6d6be8de-6c1d-11e8-8d51-ddae5596ff52.png)

重新设计设置页面，增加更多内嵌帮助   
**增加磁盘白名单**     
**增加全部复制完成后回调功能**

**Comment by kenvix** [comment]
【2018/6/16】改进开机启动设置，现在USBCopyer开机启动不会弹出UAC警告

**Comment by xingleiwu** [comment]
你好，5.0在哪里下载，谢谢了

**Comment by kenvix** [comment]
@xingleiwu 仍在开发中，进度60%

**Comment by SOcoolapk** [comment]
老哥来过！
