### ISSUE TITLE
没效果，一直是空闲状态。

### ISSUE THREAD

**Issue by kali-1** [kenvix/USBCopyer#22]
U盘是64G的金士顿，格式是NTFS，有两个分区，一个是PE用的分区。
另一个是存文件用的。
设置如图所示：
![image](https://user-images.githubusercontent.com/32212684/42086808-cfd6e448-7bc6-11e8-9292-9541a7460d69.png)
连续插拔优盘多次，还是没效果。重启程序也没啥效果。

**Comment by kali-1** [comment]
我把u盘的一个存文件用的分区的序列号写在在白名单那里。

**Comment by kali-1** [comment]
又拿移动硬盘试了下也没效果。。。
系统是64位Win10.
![image](https://user-images.githubusercontent.com/32212684/42087127-d40b769a-7bc7-11e8-879c-873750fa5e56.png)

**Comment by kenvix** [comment]
1.暂时不支持有多分区的U盘使用序列号白名单
2.白名单序列号只写了一个，却用了没列入列表的磁盘做测试
