### ISSUE TITLE
回调编码问题

### ISSUE THREAD

**Issue by qxzg** [kenvix/USBCopyer#28]
场景：
- 开启DiskDetectedCallback回调
- 操作的目录里有中文路径

在这个时候，如果我以ANSI编码保存`DiskDetectedCallback.bat`文件，那么在插入U盘后自动生成的临时文件会自动变为`UTF-8`编码，导致中文乱码。
![Snipaste_2019-04-28_20-26-45](https://user-images.githubusercontent.com/30212669/56864512-e3b98100-69f5-11e9-9045-99a70949dcc8.png)
![Snipaste_2019-04-28_20-26-52](https://user-images.githubusercontent.com/30212669/56864514-eae08f00-69f5-11e9-831c-134038cbee52.png)
而如果直接以`UTF-8`编码保存`DiskDetectedCallback.bat`文件，此时生成的临时文件虽然手动打开不会乱码，但windows执行会出现乱码

**Comment by qxzg** [comment]
已解决
手动修改注册表
```
[HKEY_CURRENT_USER\Console\%SystemRoot%_system32_cmd.exe]
"CodePage"=dword:fde9
```
以使cmd支持utf8编码

**Comment by kenvix** [comment]
在开头加入 `CHCP 936` 即可为当前cmd改变编码页。
