### ISSUE TITLE
Some suggestions for USBCopyer

### ISSUE THREAD

**Issue by EldersJavas** [kenvix/USBCopyer#33]
您好,感谢你的`USBCopyer`:

非常感谢您的`USBCopyer`,可以非常方便的静静的备份U盘文件,之前一直尝试做都不尽人意,直到看到您的`USBCopyer`才感到自愧不如.
不知您是否还在进行这个项目,暂且提一些建议:
1. 希望将设置界面做的更简练些,方便操作
2. 希望能够添加上传功能,可以直接备份<s>偷</s>到云端
例如`FTP`服务器或`NFS`,`Samba`,或者直接link到群辉.
如果您愿意添加这些功能,我会pr一些想法.

愿您的`USBCopyer`能够越做越好.

**Comment by kenvix** [comment]
非常感谢您的反馈。
`USBCopyer` 项目是我在高中时期课余时间所写的一个简单的个人项目，限于当时的技术水平，`USBCopyer` 整体的代码风格非常糟糕，可维护性较差。由于学业繁忙，我个人已经几乎无力维护此项目，未来已经不太可能添加新功能。

对于您提到的建议：
* 设置界面因我个人设计能力有限，暂时没有改良的方案
* 云端上传可以结合其他同步工具实现，例如 `FreeFileSync`
