### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Horange321** [kenvix/USBCopyer#39]
1. 做一个ComboBox，可以直接选一类扩展名。对现在教室用的触屏电脑很友好。
2. 保存配置时自动重启
3. 双击托盘图标打开设置，触摸屏上右击不是件容易的事
均已实现，可以的话可以pr

**Comment by kenvix** [comment]
欢迎您提交Pull Request

**Comment by Horange321** [comment]
> 欢迎您提交Pull Request

✔️
