### ISSUE TITLE
建议增加只复制小于50MB文件的功能

### ISSUE THREAD

**Issue by MoeYi** [kenvix/USBCopyer#5]
u盘里可能会有安装包之类的大文件，这样可以减少复制时间，尽可能在拔u盘之前复制完

**Comment by kenvix** [comment]
在计划中

**Comment by redapple0204** [comment]
不行啊....有的老师课件和视频非常大，这样子的话会导致无法拷贝
@kenvix 建议你添加这个选项但是不要强制

**Comment by kenvix** [comment]
已实现，有三种模式：不限制/大于/小于 ?MB
@redapple0204 @MoeYi

**Comment by redapple0204** [comment]
好的，thx

**Comment by MoeYi** [comment]
好的，谢谢，才看到

(你的程序让我获取到很多老师和他们孩子的照片)
