### ISSUE TITLE
建议只允许单个进程运行

### ISSUE THREAD

**Issue by Dilant** [kenvix/USBCopyer#6]
多个`USBCopyer.exe`同时运行可能导致不可预知的问题。
建议一次只允许单个进程运行。

个人建议：

当已有一个`USBCopyer.exe`在运行时，用户尝试打开另一进程，
1. 若现有进程**正在隐藏运行**，则显示其图标（切换至未隐藏运行状态）；
2. 若现有进程**未隐藏运行**，则显示“设置”界面。

--------------------分割线--------------------
话说不应该是USBCop**i**er吗=_=
（有这么个神器用，不要在意那么多啦）

**Comment by kenvix** [comment]
已实现
